gateway:
  count: 2
  gateway1:
    ip: 127.0.0.1
    port: 1234
  gateway2:
    ip: 127.0.0.1
    port: 2234

database:
  database: gw_calamp_development
  username: root
  host: localhost

queue:
  host: localhost
  port: 61613
  login: admin
  passcode: admin
  ssl: false
  name: /queue/readings

system:
  debug: true
